/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Jesus Larez
 */

import model.SecondHandShop;
import model.User;
import model.Category;
import model.Product;
import java.util.ArrayList;
import model.Purchase;
import gui.CardPayment;
import model.Selled;

public class CheckWindow extends javax.swing.JFrame {

    /**
     * Creates new form CheckWindow
     */
    SecondHandShop shop;
    User user;
    public static Purchase pur;
    ArrayList<Product> objectProduct;
    SecondHandShopFrom shopApp;
    CardPayment cardPayment;

    public CheckWindow() {
        shop = SecondHandShopFrom.shop;
        user = SecondHandShopFrom.user;
        cardPayment = null;
        objectProduct = shop.getProducts();

        
        

        initComponents();
        showAllProducts();
        showAllCategories();
        showOfferedProducts();
        showSoldProducts();
        showOngoingPurchase();
        showBoughtProducts();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        products = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        categories = new java.awt.List();
        jLabel2 = new javax.swing.JLabel();
        comprarProducto = new javax.swing.JButton();
        offeredProducts = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        addNewProduct = new javax.swing.JButton();
        newProductName = new javax.swing.JTextField();
        newProductDes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        SoldProducts = new java.awt.List();
        jLabel8 = new javax.swing.JLabel();
        ongoingProducts = new java.awt.List();
        jLabel9 = new javax.swing.JLabel();
        boughtProducts = new java.awt.List();
        jLabel10 = new javax.swing.JLabel();
        pagarProducto = new javax.swing.JButton();
        newProductCategory = new javax.swing.JComboBox();
        newProductPrice = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productDescription = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        contacDetails = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });

        jLabel1.setText("Productos ");

        categories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriesActionPerformed(evt);
            }
        });

        jLabel2.setText("Categorias ");

        comprarProducto.setText("Pedir Producto");
        comprarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarProductoActionPerformed(evt);
            }
        });

        offeredProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offeredProductsActionPerformed(evt);
            }
        });

        jLabel3.setText("Mis Productos ");

        eliminar.setText("Eliminar Producto");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        addNewProduct.setText("Añadir Producto");
        addNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProductActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Precio");

        jLabel6.setText("Desc:");

        jLabel7.setText("Categoria");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        SoldProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoldProductsActionPerformed(evt);
            }
        });

        jLabel8.setText("Productos Vendidos");

        ongoingProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ongoingProductsActionPerformed(evt);
            }
        });

        jLabel9.setText("Productos Pedidos");

        boughtProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boughtProductsActionPerformed(evt);
            }
        });

        jLabel10.setText("Productos Comprados");

        pagarProducto.setText("Pagar Producto");
        pagarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarProductoActionPerformed(evt);
            }
        });

        newProductCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libros", "Ropa", "Mujer", "Hombre", "Musica", "Comida", "Electronica", "PC", "Electrodomesticos", "Muebles", "Coches", "Belleza" }));
        newProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductCategoryActionPerformed(evt);
            }
        });

        newProductPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel11.setText("Descripcion");

        productPrice.setEditable(false);
        productPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPriceActionPerformed(evt);
            }
        });

        jLabel12.setText("Precio");

        productDescription.setEditable(false);
        productDescription.setColumns(20);
        productDescription.setLineWrap(true);
        productDescription.setRows(5);
        jScrollPane2.setViewportView(productDescription);

        contacDetails.setEditable(false);
        contacDetails.setColumns(20);
        contacDetails.setLineWrap(true);
        contacDetails.setRows(5);
        jScrollPane1.setViewportView(contacDetails);

        jLabel13.setText("Informacion de Contacto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(categories, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comprarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newProductDes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newProductName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newProductCategory, 0, 256, Short.MAX_VALUE)
                            .addComponent(newProductPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNewProduct)
                        .addGap(100, 100, 100)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offeredProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ongoingProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boughtProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(pagarProducto)
                        .addGap(347, 347, 347)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(productPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(products, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(newProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel5)
                                                    .addComponent(newProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(newProductDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(newProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(addNewProduct))
                                            .addComponent(offeredProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addComponent(eliminar)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprarProducto)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boughtProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ongoingProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SoldProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pagarProducto)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
        // TODO add your handling code here:
        Product selected;
        selected= objectProduct.get(products.getSelectedIndex());
        showDescription(selected);
        showContactDetails(selected);
        

    }//GEN-LAST:event_productsActionPerformed

    private void categoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriesActionPerformed
        // TODO add your handling code here:
        Category selected;
        selected=shop.categoryList.get(categories.getSelectedIndex());

        showCategoryItems(selected);
        
    }//GEN-LAST:event_categoriesActionPerformed

    private void offeredProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offeredProductsActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_offeredProductsActionPerformed

    private void addNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProductActionPerformed
        // TODO add your handling code here:
        float f = new Float(newProductPrice.getText());
        int i;
        Category aux = null;
        for(i = 0; i< shop.categoryList.size() ; i++){
            if(shop.categoryList.get(i).getName().equals((String)newProductCategory.getSelectedItem())){
                aux = shop.categoryList.get(i);
                shop.addProduct(user.offerProduct(newProductName.getText(), f, newProductDes.getText(), "Imagen", aux));
            }

        }
        
        showAllProducts();
        showOfferedProducts();
        
        
    }//GEN-LAST:event_addNewProductActionPerformed

    private void comprarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarProductoActionPerformed
        // TODO add your handling code here:
        Product selected;
        selected = objectProduct.get(products.getSelectedIndex());
        
        user.purchaseProduct(selected);
        shop.removeProduct(selected);

        showAllProducts();
        showOfferedProducts();
        showBoughtProducts();
        showOngoingPurchase();
        showSoldProducts();
        
    }//GEN-LAST:event_comprarProductoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        Product selected;
        ArrayList<Product> aux = user.getProducts();
        selected = aux.get(offeredProducts.getSelectedIndex());
        shop.removeProduct(selected);
        user.removeProduct(selected);
        showAllProducts();
        showOfferedProducts();

        
    }//GEN-LAST:event_eliminarActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        shopApp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void SoldProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoldProductsActionPerformed
        // TODO add your handling code here:
        showSoldProducts();

    }//GEN-LAST:event_SoldProductsActionPerformed

    private void boughtProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boughtProductsActionPerformed
        // TODO add your handling code here:
        showBoughtProducts();
    }//GEN-LAST:event_boughtProductsActionPerformed

    private void pagarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarProductoActionPerformed
        // TODO add your handling code here:
        ArrayList<Purchase> result = user.getPurchasHist();
        for(Purchase x : result){
            if(x.getState()){
                result.remove(x);
            }
        }
        pur = result.get(ongoingProducts.getSelectedIndex());
        
        cardPayment = new CardPayment();
        cardPayment.checkWindow = this;
        cardPayment.setVisible(true);
        user.sellPaid(result.get(ongoingProducts.getSelectedIndex()).getProduct());
        this.setVisible(false);
        

        
        
        
    }//GEN-LAST:event_pagarProductoActionPerformed

    private void newProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductCategoryActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_newProductCategoryActionPerformed

    private void productPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPriceActionPerformed

    private void ongoingProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ongoingProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ongoingProductsActionPerformed


    public void showAllProducts(){
       products.removeAll();
       objectProduct.clear();
       ArrayList<Product> result = shop.getProducts();
       for (Product x : result) {
           if(x.getProductOwner()!=user){
                products.add(x.getName());
                objectProduct.add(x);
           }

       }             
    }
    
    public void  showAllCategories(){
        categories.removeAll();
        ArrayList<Category> result = shop.getCategorys();
        for (Category x : result) {
            categories.add(x.getName());
        }
    }
    
    public void showCategoryItems(Category selected){
        products.removeAll();
        objectProduct.clear();
        ArrayList<Product> result = shop.getByCate(selected);
        for (Product x: result) {
            products.add(x.getName());
            objectProduct.add(x);
        }
    }
    
    public void showOfferedProducts(){
        offeredProducts.removeAll();
        ArrayList<Product> result = user.getProducts();
        for (Product x : result) {
            offeredProducts.add(x.getName());
        }
    }
    public void showBoughtProducts(){
        boughtProducts.removeAll();
        ArrayList<Purchase> result = user.getPurchasHist();
        for(Purchase x : result){
            if(x.getState()){
                boughtProducts.add(x.getProduct().getName());
            }
        }
    }
    public void showOngoingPurchase(){
        ongoingProducts.removeAll();
        ArrayList<Purchase> result = user.getPurchasHist();
        for(Purchase x : result){
            if(!x.getState()){
                ongoingProducts.add(x.getProduct().getName());
            }
        }
    }
    public void showSoldProducts(){
        SoldProducts.removeAll();
        ArrayList<Selled> result = user.getSoldProducts();
        for(Selled x : result) {
            SoldProducts.add(x.getProduct().getName());
            System.out.println(x.getProduct().getName());
        }
    }
    public void showDescription(Product selected){
        productDescription.setText(selected.getDescription());
        productPrice.setText(selected.getPrice() + "");
    }
    public void showContactDetails(Product selected){
        contacDetails.setText(selected.getProductOwner().getName() + "\n" + selected.getProductOwner().getEmail());
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckWindow().setVisible(false);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List SoldProducts;
    private javax.swing.JButton addNewProduct;
    private java.awt.List boughtProducts;
    private java.awt.List categories;
    private javax.swing.JButton comprarProducto;
    private javax.swing.JTextArea contacDetails;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JComboBox newProductCategory;
    private javax.swing.JTextField newProductDes;
    private javax.swing.JTextField newProductName;
    private javax.swing.JFormattedTextField newProductPrice;
    private java.awt.List offeredProducts;
    private java.awt.List ongoingProducts;
    private javax.swing.JButton pagarProducto;
    private javax.swing.JTextArea productDescription;
    private javax.swing.JTextField productPrice;
    private java.awt.List products;
    // End of variables declaration//GEN-END:variables
}
